export const FETCH_WEATHER = 'FETCH_WEATHER';
export const NEW_REMINDER = 'NEW_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const FETCH_CITIES = 'FETCH_CITIES';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const GET_CURRENT_REMINDER = 'GET_CURRENT_REMINDER';
export const DELETE_REMINDERS = 'DELETE_REMINDERS';